# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7e3650e354bd3a0542516d4fc2cd58177c97cb829c8c5ad331fb3996eff90a6bf3ddcfe94b74f3137147bc9f762778dc89671d96123d0171bf5f0c3f03d265f

test:
  secret_key_base: e3ad7824dec9781ada32132d7ebda71c1494a8e3650946bdb76dec4bb733ba09e63ac87b3872245e380459a391c3658044d5d2dc053f4c56e93ad9932d5ea694

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
